syntax = "proto3";

package DockerController;

import "google/protobuf/empty.proto";
import "proto/resources.messages.proto";
import "proto/container.proto";
import "proto/compose.proto";

option go_package = "DockerController/gen/docker_controller_v1";

service DockerService {
  rpc GetInfo(google.protobuf.Empty) returns (DockerInfo);
  rpc GetResourceUsage(google.protobuf.Empty) returns (ResourceUsage);
  rpc StreamEvents(StreamEventsRequest) returns (stream Event);
  rpc Ping(google.protobuf.Empty) returns (google.protobuf.Empty);

  rpc ListContainers(google.protobuf.Empty) returns (ListContainersResponse);
  rpc ListProjects(google.protobuf.Empty) returns (ListProjectsResponse);
}

message DockerInfo {
  int32 containers_running = 1;
  int32 containers_stopped = 2;
  int32 images_count = 3;
  string os = 4;
  string architecture = 5;
  uint64 total_memory = 6;
  int32 cpus = 7;
}

message StreamEventsRequest {
  repeated string types = 1;
  repeated string actions = 2;
}

message Event {
  string type = 1;
  string action = 2;
  string actor_id = 3;
  string actor_name = 4;
  int64 time = 5;
  map<string, string> attributes = 6;
}

message ListContainersResponse {
  repeated Container containers = 1;
}

message ListProjectsResponse {
  repeated Project projects = 1;
}